### ISSUE TITLE
Best Queso Recipe... go!

### ISSUE THREAD

**Issue by subdigital** [jwo/feedback#4]
My entire outlook of you as a human depends on your response.  You were born for this.  Good luck!

**Comment by jwo** [comment]
There's no one right answer, but let's give it a try.

# Occasions for queso

### When you want something around friends, with other food present
- [Rotel + Queso](http://www.ro-tel.com/recipes-RoTel-Famous-Queso-Dip-2693.html) 

It's a fan favorite because it works. Use a slow cooker with about 40 minutes, and you're done. It won't win any conversations about being hip and kinds of cheese, but you won't have too: people will be too easy eating it.
![img_2693_512](https://f.cloud.github.com/assets/123075/2004035/cb8ec5c4-8691-11e3-82f2-e8d42519cc44.jpg)

### Not a party, but it's the highlight of the food around it
- [Suped Up Rotel](http://www.weeatt.com/recipes/super-queso) 

This is a variation on a theme, and includes some unique ingredients, including meat and mushrooms. Works well if you have a bunch of chips an maybe wings next to it. Conversation about the queso will rise to "This queso is great!"

![velveeta_spicy_sausage_dip](https://f.cloud.github.com/assets/123075/2004037/09f0a756-8692-11e3-800f-cdfb6de9d518.jpg)

### You want to talk about the queso
- [Homemade](http://www.homesicktexan.com/2008/04/more-natural-chile-con-queso.html) From scratch, starting from butter and flour, ending with longhorn cheddar and monterrey jack.

![quesodsc_2582](https://f.cloud.github.com/assets/123075/2004034/bb7f6d50-8691-11e3-8a05-b6ed85db8e00.JPG)

Things you can do to make it more #hipster
1. Add some meltable cheeses (Emmenthaler, Gruyere, and Comte) [Credit](http://www.thekitchn.com/cheese-on-melting-the-cheesemo-88264)
2. Go with some bacon, sausage, and unique chiles

### Outside the box
- [Queso Flameado](http://www.homesicktexan.com/2010/01/queso-flameado-recipe.html) 

This brings back so many memories, mostly by the pool with the grandparents. You should do these with [home made flour tortillas](http://thepioneerwoman.com/cooking/2010/05/homemade-flour-tortillas/) (or at least, home cooked tortillas)

![queso-flameado_dsc7049](https://f.cloud.github.com/assets/123075/2004041/7ce38616-8692-11e3-81cd-a267d010d4de.jpg)
