### ISSUE TITLE
Freelancing

### ISSUE THREAD

**Issue by cguirgui** [jwo/feedback#5]
Hey Jesse

I have a full-time job currently, but I've been dabbling in code for the last 6 months before and after work. It's not a bad job, but I want to make the switch to web developer. The problem is that no one will give me a job without experience, which is why your email 'from employee to freelance' appealed to me. 

My one fear about freelance is that there are other people who have been doing freelancing/consulting for years, and are much more experienced that I am, and that I would be left looking for scraps in these markets. Am I right to think this way? 

Would love to know your thoughts!

Cyril

**Comment by jwo** [comment]
Cyril --

> The problem is that no one will give me a job without experience, which is why your email 'from employee to freelance' appealed to me. 

Yeah, totally -- and it can be hard to get a job paying anywhere close to your current salary. I found I was in "golden handcuffs" (that weren't all that golden). I do see freelancing as a way out, as you see it.

> My one fear about freelance is that there are other people who have been doing freelancing/consulting for years, and are much more experienced that I am, and that I would be left looking for scraps in these markets. Am I right to think this way? 

So the thing is, those freelancers who have been doing it for years increase their rates every year. But some clients don't want to pay $100/$150/$200 an hour. They can afford $50-$75 an hour. That's your target market.

And, those clients who have increased their rates tend to drop clients. Sooo those freelancers who you were originally afraid of competing against really become your best source of leads.

I'd email one of them and ask if they had any clients they had to drop because of their increased rates. Then, email those clients and see if they have any needs you can solve. Check out http://emailsthatwin.com/ on cold-emailing techniques.

Hope that helps! Is it OK with you if I use this in my upcoming [Tex Mex Consulting](http://texmexconsulting.com/) book under Q&A?
- jesse

**Comment by codeodor** [comment]
One other thing to add -- some of those may not have even dropped clients, but could use someone as a subcontractor or even just send referrals your way because they're too busy to handle any more work.

**Comment by jwo** [comment]
A+ as subcontractor @codeodor -- I totally believe other people are a perfect source of leads in exactly the way you describe.

**Comment by cguirgui** [comment]
Very interesting! That makes sense, and I love the strategy of calling
freelancers and asking about dropped clients. Feel free to use it in your Q
and A Jesse, I appreciate the response.
